# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 563bd55af73ff49d74bc3bd762abfaa9badad10ea3fb173023e2f3992e58fd394d366b7d7f3978daa24fe3b22875f39d3da6f1c510ed4083b3ac32ab70caa382

test:
  secret_key_base: 7554bd3b2f1cdad57c498d8ac393bdc3f59d28f95c2cfc8841a57ef7240c934b84cebc8df7aea03310925ca040e91042d68eea9e694af83abe6413891192e1ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
